title: CV-Andrei-Martianov
description: Developer CV.
url: https://cv.an-mart.com/
baseurl: ""
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-minifier

exclude:
  - docker-compose.yml
